version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"
    versioning-strategy: increase
    commit-message:
      prefix: deps
      include: scope

    pull-request-branch-name:
      separator: "-"
      prefix: dependabot

    labels:
      - dependencies
      - dependabot
