[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "agentgrunt"
version = "0.1.6"
description = "Agent Grunt"
authors = [
  { name = "Nik V <github@nikvdp.com>" },
  { name = "Jeremiah K. <jeremiahk@gmx.com>" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
  "fastapi",
  "httpx",
  "plumbum",
  "pydantic",
  "pyperclip",
  "pytest",
  "tqdm",
  "typer",
]

[project.scripts]
agentgrunt = "agentgrunt.main:app"

[tool.trunk]
enabled = true

[tool.coverage.run]
branch = true
source = ["agentgrunt"]

[tool.coverage.report]
show_missing = true
skip_covered = true
