name: ci

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Fetch all branches
        run: git fetch --prune --unshallow --all

      - name: Install Trunk
        run: curl https://get.trunk.io -fsSL | bash

      - name: Add Trunk to PATH
        run: export PATH="$HOME/.trunk/bin:$PATH"

      - name: Run Trunk check
        run: poetry run trunk check

      - name: Run tests
        run: poetry run pytest
