name: ci

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python and install Poetry
        run: |
          python --version
          pip install poetry
          poetry --version
      - name: Install dependencies and validate
        run: |
          poetry install
          poetry check
          poetry lock
      - name: Run trunk check
        run: poetry run trunk check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python and install Poetry
        run: |
          python --version
          pip install poetry
          poetry --version
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest
